# Generated by Django 3.1.6 on 2021-12-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='CRM.customer'),
        ),
    ]
