# Generated by Django 3.1.6 on 2021-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20211206_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
