# Generated by Django 3.1.6 on 2021-12-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_pipeline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='URL',
            new_name='company_URL',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='company_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
