# Generated by Django 3.1.6 on 2021-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_company_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='pipe_line',
            new_name='pipeline',
        ),
        migrations.RenameField(
            model_name='pipelinestage',
            old_name='pipe_line',
            new_name='pipeline',
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='guidance',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
