# Generated by Django 3.1.6 on 2021-12-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20211221_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.unit'),
            preserve_default=False,
        ),
    ]
