# Generated by Django 3.1.6 on 2021-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20211227_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='people',
            field=models.ManyToManyField(to='CRM.CompanyMember'),
        ),
    ]
