# Generated by Django 3.1.6 on 2021-12-31 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_lead_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='opened_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
