# Generated by Django 3.1.6 on 2021-12-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_lead_opened_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
        migrations.CreateModel(
            name='TaskProgessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.task')),
            ],
        ),
        migrations.CreateModel(
            name='LeadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.lead')),
                ('task_lines', models.ManyToManyField(to='CRM.TaskProgessLine')),
            ],
        ),
    ]
