# Generated by Django 3.1.6 on 2022-01-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_leadloss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leads', to='CRM.pipeline'),
        ),
    ]
