# Generated by Django 3.1.6 on 2022-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_auto_20220106_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_target',
            field=models.FloatField(blank=True, default=1000, null=True),
        ),
    ]
