# Generated by Django 3.1.6 on 2022-01-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_customer_sales_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadloss',
            name='customer',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='customer_losses', to='CRM.customer'),
            preserve_default=False,
        ),
    ]
